### ISSUE TITLE
Barre de recherche, localisation, filtre de rayon

### ISSUE THREAD

**Issue by NefytZ** [WildCodeSchool/202209-orleans-php-project-externatic#322]
En version mobile ( Iphone XR ) celle ci ce wrap

**Comment by shvilaine** [comment]
Commentaire supplémentaire: Ne se wrap pas chez moi, donne des champs tout petits

![Capture d’écran du 2023-01-30 15-55-44](https://user-images.githubusercontent.com/83545466/215511709-7f206591-2c13-4286-b9dc-9c8ebb8d521d.png)

**Comment by williambouet** [comment]
done
