### ISSUE TITLE
Register Form 

### ISSUE THREAD

**Issue by NefytZ** [WildCodeSchool/202209-orleans-php-project-externatic#324]
Centré sur la gauche de la page
(á verifier)

**Comment by NefytZ** [comment]
<img width="1440" alt="Capture d’écran 2023-01-30 à 15 56 03" src="https://user-images.githubusercontent.com/91143617/215511903-16ceae53-f315-4947-be6c-0b3eeb05b894.png">

**Comment by shvilaine** [comment]
Version mobile: 
![Capture d’écran du 2023-01-30 16-04-38](https://user-images.githubusercontent.com/83545466/215514015-1c72b8ac-eaed-4234-8baa-ff83bab1a65e.png)

**Comment by williambouet** [comment]
done
